#ifndef JSVALUE_H
#define JSVALUE_H

namespace mapleir {
typedef enum JsvalTag {
  JSVALTAGUNDEFINED = 0,
  JSVALTAGNULL,
  JSVALTAGBOOLEAN,
  JSVALTAGINT32,
  JSVALTAGSTRING,
  JSVALTAGOBJECT,
  JSVALTAGUNKNOWN,
  JSVALTAGELEMHOLE,
}JsvalTag;

// Bit is set for 16-bit code units
#define JSSTRING_UNICODE ((uint8_t)0x01)
// Bit is set for non-const code units
#define JSSTRING_GEN ((uint8_t)0x02)
// Bit is set for large strs whose length > 255 
#define JSSTRING_LARGE ((uint8_t)0x04)

typedef enum {
  JS_BUILTIN_GLOBAL = 0,
  JS_BUILTIN_OBJECT,
  JS_BUILTIN_OBJECT_PROTOTYPE,
  JS_BUILTIN_FUNCTION,
  JS_BUILTIN_FUNCTION_PROTOTYPE,
  JS_BUILTIN_ARRAY,
  JS_BUILTIN_ARRAY_PROTOTYPE,
  JS_BUILTIN_STRING,
  JS_BUILTIN_STRING_PROTOTYPE,
  JS_BUILTIN_BOOLEAN,
  JS_BUILTIN_BOOLEAN_PROTOTYPE,
  JS_BUILTIN_NUMBER,
  JS_BUILTIN_NUMBER_PROTOTYPE,
  JS_BUILTIN_COUNT
} js_builtin_id;
}
#endif
